### ISSUE TITLE
datasource-proxy slow-query logging doesn't work as expected

### ISSUE THREAD

**Issue by rolandkozma-sg** [gavlyukovskiy/spring-boot-data-source-decorator#128]
Hi,
 I'm using **datasource-proxy-spring-boot-starter** **1.8.1** with **spring boot 2.5.15**.
Beside adding the above dependency, I also configured:
**decorator.datasource.datasource-proxy.query.log-level**=INFO
Then I started to see the queries logged at the info level, as expected.

However, I wasn't able to configure slow-queries to be logged using the properties:
decorator.datasource.datasource-proxy.slow-query.enable-logging=true
decorator.datasource.datasource-proxy.slow-query.log-level=WARN
decorator.datasource.datasource-proxy.slow-query.threshold=50

I'd like to log at WARN level all the queries that took longer than 50 milliseconds (although the doc says that the threshold property value is in seconds, I think that's a mistake).
After adding the above slow-query configs I still see all the logs at INFO level including the queries with longer execution time than 50 ms.
The only way I'm able to see logs at WARN level is to set the threshold to 0. Then all the logs will be with WARN.
My goal is to log only slow-queries at WARN level. Please help.

Regards,
Roland

**Comment by pcomp96** [comment]
Same problem for us : 

SpringBoot 3.4.3 
datasource-proxy-spring-boot-starter.version = 1.10.0

This our config:

```yaml
decorator:
  datasource:
    enabled: true #Enable the decorator
    datasource-proxy:
      # Use only one of this
      multiline: false
      json-format: false
      format-sql: true
      slow-query:
        enable-logging: true
        threshold: 300 #Default threshold value Log for slow query
        log-level: WARN #default
      query:
        enable-logging: true #default
        log-level: DEBUG #default
```

I have the slow query (305 over my threshold) logged on SLF4JQueryLoggingListener 

2025-03-27 15:02:38.291 DEBUG 73 --- [x-pool-1] [67e5688dcf1ec74a0fb65d84006455ba-57ebbe8fcae5f5c9] n.t.d.l.l.SLF4JQueryLoggingListener      : Name:main, Connection:163845, Time:305, Success:True, Type:Prepar....

**Comment by gavlyukovskiy** [comment]
The values are in seconds, so for `threshold=50`, it means that query needs to take 50 seconds to be written in the logs. 

@pcomp96 `SLF4JQueryLoggingListener` logs all queries regardless of their time, so that's why you see a log line.

With configuration:
```yaml
decorator:
  datasource:
    datasource-proxy:
      format-sql: true
      query:
        log-level: INFO
      slow-query:
        threshold: 1
```
and simulating the sleep inside a query I correctly get two log

```
2025-03-30T11:03:01.117+02:00  WARN 11122 --- [datasource-proxy-sample] [pool-2-thread-1] n.t.d.l.logging.SLF4JSlowQueryListener   : 
Name:h2, Connection:2, Time:1000, Success:False
Type:Prepared, Batch:False, QuerySize:1, BatchSize:0
Query:["SELECT
  SLEEP(?)"]
Params:[(3000)]
2025-03-30T11:03:03.126+02:00  INFO 11122 --- [datasource-proxy-sample] [nio-8081-exec-1] n.t.d.l.l.SLF4JQueryLoggingListener      : 
Name:h2, Connection:2, Time:3010, Success:True
Type:Prepared, Batch:False, QuerySize:1, BatchSize:0
Query:["SELECT
  SLEEP(?)"]
Params:[(3000)]
```
