### ISSUE TITLE
Possible memory leak - datasource proxy

### ISSUE THREAD

**Issue by tomorrow10** [gavlyukovskiy/spring-boot-data-source-decorator#29]
Hello, today I have come across possible memory leak in datasource proxy inside `TracingListenerStrategy`

After 250k requests to server, the strategy instance acumulates nearly 900MB of memory and never releases it.

![image](https://user-images.githubusercontent.com/28731780/55315470-af8d8780-546c-11e9-9e0e-59c1abd6044e.png)

I have latest version of datasource proxy spring boot starter. 

```
        <dependency>
            <groupId>com.github.gavlyukovskiy</groupId>
            <artifactId>datasource-proxy-spring-boot-starter</artifactId>
            <version>1.5.3</version>
        </dependency>
```

configuration properties

```
decorator:
  datasource:
    datasource-proxy:
      query:
        enable-logging: false
      slow-query:
        threshold: 1
      count-query: true
```
When using p6spy, the problem does not seem to be present.
