### ISSUE TITLE
Proposal: Support all p6spy settings via application.yml

### ISSUE THREAD

**Issue by domschmidt** [gavlyukovskiy/spring-boot-data-source-decorator#71]
In a spring cloud setup it would be very helpfully, if we could configure all parameters via application.yml

e.g.

application.yml
```
decorator:
  datasource:
    p6spy:
      config:
        excludecategories:
```
