### ISSUE TITLE
datasource-proxy-sample is not writing query logs 

### ISSUE THREAD

**Issue by gtiwari333** [gavlyukovskiy/spring-boot-data-source-decorator#81]
NOT A BUG!

When I run endpoints from SampleController or when I run tests, the `datasource-proxy-sample` module is not producing any logs into console. My first thought was there's something broken with the library. But later I found its due to the default log levels on the config. 

I needed to change the log level with one of the following:

```
logging:
  level:
    net.ttddyy.dsproxy.listener.logging: DEBUG
```

OR 

```
decorator:
  datasource:
    datasource-proxy:
      query:
        log-level: INFO
```

Please document this somewhere on the README file so that people won't run into any confusion. Let me you if you accept PRs.
